import { GET_USERS, GET_MESSAGES } from "./queries";
import {
  INSERT_USER_MAIN,
  INSERT_NEW_USER_FOR_DATA,
  UPDATE_USER_MESSAGES,
  UPDATE_USER_NAME_BACKUP,
} from "./mutations";

// Mutations
export {
  INSERT_USER_MAIN,
  INSERT_NEW_USER_FOR_DATA,
  UPDATE_USER_MESSAGES,
  UPDATE_USER_NAME_BACKUP,
};

// Queries
export { GET_USERS, GET_MESSAGES };
